# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier_urllib3
from tradier_urllib3.models.streaming_quote import StreamingQuote  # noqa: E501
from tradier_urllib3.rest import ApiException

class TestStreamingQuote(unittest.TestCase):
    """StreamingQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StreamingQuote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier_urllib3.models.streaming_quote.StreamingQuote()  # noqa: E501
        if include_optional :
            return StreamingQuote(
                ask = 1.337, 
                askdate = 'a', 
                askexch = '0', 
                asksz = 1.337, 
                bid = 1.337, 
                biddate = 'a', 
                bidexch = '0', 
                symbol = '0', 
                type = '0'
            )
        else :
            return StreamingQuote(
        )

    def testStreamingQuote(self):
        """Test StreamingQuote"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
