# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier_asyncio
from tradier_asyncio.models.streaming_summary import StreamingSummary  # noqa: E501
from tradier_asyncio.rest import ApiException

class TestStreamingSummary(unittest.TestCase):
    """StreamingSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StreamingSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier_asyncio.models.streaming_summary.StreamingSummary()  # noqa: E501
        if include_optional :
            return StreamingSummary(
                high = 1.337, 
                low = 1.337, 
                open = 1.337, 
                prev_close = 1.337, 
                symbol = '0', 
                type = '0'
            )
        else :
            return StreamingSummary(
        )

    def testStreamingSummary(self):
        """Test StreamingSummary"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
