# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier_asyncio
from tradier_asyncio.models.profile_profile_account import ProfileProfileAccount  # noqa: E501
from tradier_asyncio.rest import ApiException

class TestProfileProfileAccount(unittest.TestCase):
    """ProfileProfileAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProfileProfileAccount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier_asyncio.models.profile_profile_account.ProfileProfileAccount()  # noqa: E501
        if include_optional :
            return ProfileProfileAccount(
                account_number = '0', 
                classification = '0', 
                day_trader = True
            )
        else :
            return ProfileProfileAccount(
        )

    def testProfileProfileAccount(self):
        """Test ProfileProfileAccount"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
