# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier_asyncio
from tradier_asyncio.models.inline_response2_xx_options import InlineResponse2XXOptions  # noqa: E501
from tradier_asyncio.rest import ApiException

class TestInlineResponse2XXOptions(unittest.TestCase):
    """InlineResponse2XXOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2XXOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier_asyncio.models.inline_response2_xx_options.InlineResponse2XXOptions()  # noqa: E501
        if include_optional :
            return InlineResponse2XXOptions(
                option = [
                    tradier_asyncio.models.option.option(
                        symbol = '0', 
                        description = '0', 
                        exch = '0', 
                        last = 1.337, 
                        change = 1.337, 
                        volume = 1.337, 
                        open = 1.337, 
                        high = 1.337, 
                        low = 1.337, 
                        close = 1.337, 
                        bid = 1.337, 
                        ask = 1.337, 
                        underlying = '0', 
                        strike = 1.337, 
                        change_percentage = 1.337, 
                        average_volume = 1.337, 
                        last_volume = 1.337, 
                        trade_date = 1.337, 
                        prevclose = 1.337, 
                        week_52_high = 1.337, 
                        week_52_low = 1.337, 
                        bidsize = 1.337, 
                        bidexch = '0', 
                        bid_date = 1.337, 
                        asksize = 1.337, 
                        ask_date = 1.337, 
                        open_interest = 1.337, 
                        contract_size = 1.337, 
                        expiration_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        expiration_type = 'standard', 
                        option_type = 'call', 
                        root_symbol = '0', 
                        greeks = tradier_asyncio.models.option_greeks.option_greeks(
                            delta = 1.337, 
                            gamma = 1.337, 
                            thetha = 1.337, 
                            vega = 1.337, 
                            rho = 1.337, 
                            phi = 1.337, 
                            bid_iv = 1.337, 
                            mid_iv = 1.337, 
                            ask_iv = 1.337, 
                            smv_vol = 1.337, 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ]
            )
        else :
            return InlineResponse2XXOptions(
        )

    def testInlineResponse2XXOptions(self):
        """Test InlineResponse2XXOptions"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
