# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier
from tradier.models.history import History  # noqa: E501
from tradier.rest import ApiException

class TestHistory(unittest.TestCase):
    """History unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test History
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier.models.history.History()  # noqa: E501
        if include_optional :
            return History(
                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                open = 1.337, 
                high = 1.337, 
                low = 1.337, 
                close = 1.337, 
                volume = 1.337
            )
        else :
            return History(
        )

    def testHistory(self):
        """Test History"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
