# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier
from tradier.models.inline_response2_xx5 import InlineResponse2XX5  # noqa: E501
from tradier.rest import ApiException

class TestInlineResponse2XX5(unittest.TestCase):
    """InlineResponse2XX5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2XX5
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier.models.inline_response2_xx5.InlineResponse2XX5()  # noqa: E501
        if include_optional :
            return InlineResponse2XX5(
                history = tradier.models.inline_response_2_xx_5_history.inline_response_2XX_5_history(
                    day = None, 
                    month = None, 
                    week = None, )
            )
        else :
            return InlineResponse2XX5(
        )

    def testInlineResponse2XX5(self):
        """Test InlineResponse2XX5"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
