# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier
from tradier.models.inline_response2_xx4_profile import InlineResponse2XX4Profile  # noqa: E501
from tradier.rest import ApiException

class TestInlineResponse2XX4Profile(unittest.TestCase):
    """InlineResponse2XX4Profile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2XX4Profile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier.models.inline_response2_xx4_profile.InlineResponse2XX4Profile()  # noqa: E501
        if include_optional :
            return InlineResponse2XX4Profile(
                account = [
                    tradier.models.inline_response_2_xx_4_profile_account.inline_response_2XX_4_profile_account(
                        account_number = '0', 
                        classification = '0', 
                        day_trader = True, )
                    ]
            )
        else :
            return InlineResponse2XX4Profile(
        )

    def testInlineResponse2XX4Profile(self):
        """Test InlineResponse2XX4Profile"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
