# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier
from tradier.models.quote import Quote  # noqa: E501
from tradier.rest import ApiException

class TestQuote(unittest.TestCase):
    """Quote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Quote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier.models.quote.Quote()  # noqa: E501
        if include_optional :
            return Quote(
                symbol = None, 
                description = '0', 
                exch = '0', 
                last = 1.337, 
                change = 1.337, 
                volume = 1.337, 
                open = 1.337, 
                high = 1.337, 
                low = 1.337, 
                close = 1.337, 
                bid = 1.337, 
                ask = 1.337, 
                change_percentage = 1.337, 
                average_volume = 1.337, 
                last_volume = 1.337, 
                trade_date = 1.337, 
                prevclose = 1.337, 
                week_52_high = 1.337, 
                week_52_low = 1.337, 
                bidsize = 1.337, 
                bidexch = '0', 
                bid_date = 1.337, 
                asksize = 1.337, 
                askexch = '0', 
                ask_date = 1.337, 
                root_symbols = None
            )
        else :
            return Quote(
        )

    def testQuote(self):
        """Test Quote"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
