# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tradier_asyncio.configuration import Configuration


class InlineResponse2XX1(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'expirations': 'InlineResponse2XX1Expirations'
    }

    attribute_map = {
        'expirations': 'expirations'
    }

    def __init__(self, expirations=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse2XX1 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._expirations = None
        self.discriminator = None

        self.expirations = expirations

    @property
    def expirations(self):
        """Gets the expirations of this InlineResponse2XX1.  # noqa: E501


        :return: The expirations of this InlineResponse2XX1.  # noqa: E501
        :rtype: InlineResponse2XX1Expirations
        """
        return self._expirations

    @expirations.setter
    def expirations(self, expirations):
        """Sets the expirations of this InlineResponse2XX1.


        :param expirations: The expirations of this InlineResponse2XX1.  # noqa: E501
        :type: InlineResponse2XX1Expirations
        """
        if self.local_vars_configuration.client_side_validation and expirations is None:  # noqa: E501
            raise ValueError("Invalid value for `expirations`, must not be `None`")  # noqa: E501

        self._expirations = expirations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2XX1):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2XX1):
            return True

        return self.to_dict() != other.to_dict()
