# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tradier_asyncio.configuration import Configuration


class StreamingSummary(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'high': 'float',
        'low': 'float',
        'open': 'float',
        'prev_close': 'float',
        'symbol': 'str',
        'type': 'str'
    }

    attribute_map = {
        'high': 'high',
        'low': 'low',
        'open': 'open',
        'prev_close': 'prevClose',
        'symbol': 'symbol',
        'type': 'type'
    }

    def __init__(self, high=None, low=None, open=None, prev_close=None, symbol=None, type=None, local_vars_configuration=None):  # noqa: E501
        """StreamingSummary - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._high = None
        self._low = None
        self._open = None
        self._prev_close = None
        self._symbol = None
        self._type = None
        self.discriminator = None

        if high is not None:
            self.high = high
        if low is not None:
            self.low = low
        if open is not None:
            self.open = open
        if prev_close is not None:
            self.prev_close = prev_close
        if symbol is not None:
            self.symbol = symbol
        if type is not None:
            self.type = type

    @property
    def high(self):
        """Gets the high of this StreamingSummary.  # noqa: E501


        :return: The high of this StreamingSummary.  # noqa: E501
        :rtype: float
        """
        return self._high

    @high.setter
    def high(self, high):
        """Sets the high of this StreamingSummary.


        :param high: The high of this StreamingSummary.  # noqa: E501
        :type: float
        """

        self._high = high

    @property
    def low(self):
        """Gets the low of this StreamingSummary.  # noqa: E501


        :return: The low of this StreamingSummary.  # noqa: E501
        :rtype: float
        """
        return self._low

    @low.setter
    def low(self, low):
        """Sets the low of this StreamingSummary.


        :param low: The low of this StreamingSummary.  # noqa: E501
        :type: float
        """

        self._low = low

    @property
    def open(self):
        """Gets the open of this StreamingSummary.  # noqa: E501


        :return: The open of this StreamingSummary.  # noqa: E501
        :rtype: float
        """
        return self._open

    @open.setter
    def open(self, open):
        """Sets the open of this StreamingSummary.


        :param open: The open of this StreamingSummary.  # noqa: E501
        :type: float
        """

        self._open = open

    @property
    def prev_close(self):
        """Gets the prev_close of this StreamingSummary.  # noqa: E501


        :return: The prev_close of this StreamingSummary.  # noqa: E501
        :rtype: float
        """
        return self._prev_close

    @prev_close.setter
    def prev_close(self, prev_close):
        """Sets the prev_close of this StreamingSummary.


        :param prev_close: The prev_close of this StreamingSummary.  # noqa: E501
        :type: float
        """

        self._prev_close = prev_close

    @property
    def symbol(self):
        """Gets the symbol of this StreamingSummary.  # noqa: E501


        :return: The symbol of this StreamingSummary.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this StreamingSummary.


        :param symbol: The symbol of this StreamingSummary.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def type(self):
        """Gets the type of this StreamingSummary.  # noqa: E501


        :return: The type of this StreamingSummary.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StreamingSummary.


        :param type: The type of this StreamingSummary.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StreamingSummary):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StreamingSummary):
            return True

        return self.to_dict() != other.to_dict()
