/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx4Stream struct for InlineResponse2Xx4Stream
type InlineResponse2Xx4Stream struct {
	Url string `json:"url,omitempty"`
	Sessionid string `json:"sessionid,omitempty"`
}
