/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// StreamingSummary struct for StreamingSummary
type StreamingSummary struct {
	High float32 `json:"high,omitempty"`
	Low float32 `json:"low,omitempty"`
	Open float32 `json:"open,omitempty"`
	PrevClose float32 `json:"prevClose,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Type string `json:"type,omitempty"`
}
