/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx struct for InlineResponse2Xx
type InlineResponse2Xx struct {
	Options InlineResponse2XxOptions `json:"options,omitempty"`
}
