/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx3 struct for InlineResponse2Xx3
type InlineResponse2Xx3 struct {
	Symbols []InlineResponse2Xx3Symbols `json:"symbols,omitempty"`
}
