/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// ProfileProfileAccount struct for ProfileProfileAccount
type ProfileProfileAccount struct {
	AccountNumber string `json:"account_number,omitempty"`
	Classification string `json:"classification,omitempty"`
	DayTrader bool `json:"day_trader,omitempty"`
}
