/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// StreamingQuote struct for StreamingQuote
type StreamingQuote struct {
	Ask float32 `json:"ask,omitempty"`
	Askdate string `json:"askdate,omitempty"`
	Askexch string `json:"askexch,omitempty"`
	Asksz float32 `json:"asksz,omitempty"`
	Bid float32 `json:"bid,omitempty"`
	Biddate string `json:"biddate,omitempty"`
	Bidexch string `json:"bidexch,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Type string `json:"type,omitempty"`
}
