/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
import (
	"time"
)
// OptionGreeks struct for OptionGreeks
type OptionGreeks struct {
	// Delta (Δ) represents the rate of change between the option's price and a $1 change in the underlying asset's price.
	Delta float64 `json:"delta,omitempty"`
	// Gamma (Γ) represents the rate of change between an option's delta and the underlying asset's price.
	Gamma float64 `json:"gamma,omitempty"`
	// Theta (Θ) represents the rate of change between the option price and time, or time sensitivity - sometimes known as an option's time decay.
	Thetha float64 `json:"thetha,omitempty"`
	// Vega (v) represents the rate of change between an option's value and the underlying asset's implied volatility.
	Vega float64 `json:"vega,omitempty"`
	// Rho (p) represents the rate of change between an option's value and a 1% change in the interest rate.
	Rho float64 `json:"rho,omitempty"`
	// Phi indicates the expected change in the option premium due to a small change in the foreign currency interest rate.
	Phi float64 `json:"phi,omitempty"`
	// Bid implied volatility
	BidIv float32 `json:"bid_iv,omitempty"`
	// Mid implied volatility
	MidIv float32 `json:"mid_iv,omitempty"`
	// Ask implied volatility
	AskIv float32 `json:"ask_iv,omitempty"`
	// ORATS final implied volatility
	SmvVol float32 `json:"smv_vol,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
