/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx1ExpirationsStrikes struct for InlineResponse2Xx1ExpirationsStrikes
type InlineResponse2Xx1ExpirationsStrikes struct {
	Strike []float32 `json:"strike,omitempty"`
}
