/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// Profile struct for Profile
type Profile struct {
	Profile ProfileProfile `json:"profile,omitempty"`
}
