/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx2Strikes struct for InlineResponse2Xx2Strikes
type InlineResponse2Xx2Strikes struct {
	Strike []float32 `json:"strike,omitempty"`
}
