/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx5HistoryDay struct for InlineResponse2Xx5HistoryDay
type InlineResponse2Xx5HistoryDay struct {
	Date string `json:"date,omitempty"`
	Open float32 `json:"open,omitempty"`
	High float32 `json:"high,omitempty"`
	Low float32 `json:"low,omitempty"`
	Close float32 `json:"close,omitempty"`
	Volume float32 `json:"volume,omitempty"`
}
