/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx2 struct for InlineResponse2Xx2
type InlineResponse2Xx2 struct {
	Strikes InlineResponse2Xx2Strikes `json:"strikes,omitempty"`
}
