/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// Quote struct for Quote
type Quote struct {
	Symbol string `json:"symbol,omitempty"`
	Description string `json:"description,omitempty"`
	Exch string `json:"exch,omitempty"`
	Type string `json:"type,omitempty"`
	Last float32 `json:"last,omitempty"`
	Change float32 `json:"change,omitempty"`
	Volume float32 `json:"volume,omitempty"`
	Open float32 `json:"open,omitempty"`
	High float32 `json:"high,omitempty"`
	Low float32 `json:"low,omitempty"`
	Close float32 `json:"close,omitempty"`
	Bid float32 `json:"bid,omitempty"`
	Ask float32 `json:"ask,omitempty"`
	ChangePercentage float32 `json:"change_percentage,omitempty"`
	AverageVolume float32 `json:"average_volume,omitempty"`
	LastVolume float32 `json:"last_volume,omitempty"`
	// Unix time of trade
	TradeDate float32 `json:"trade_date,omitempty"`
	Prevclose float32 `json:"prevclose,omitempty"`
	Week52High float32 `json:"week_52_high,omitempty"`
	Week52Low float32 `json:"week_52_low,omitempty"`
	Bidsize float32 `json:"bidsize,omitempty"`
	Bidexch string `json:"bidexch,omitempty"`
	// Unix time of bid
	BidDate float32 `json:"bid_date,omitempty"`
	Asksize float32 `json:"asksize,omitempty"`
	Askexch string `json:"askexch,omitempty"`
	// Unix time of ask
	AskDate float32 `json:"ask_date,omitempty"`
	// Comma-delimited list of option root symbols for an underlier
	RootSymbols string `json:"root_symbols,omitempty"`
	RootSymbol string `json:"root_symbol,omitempty"`
	// Underlying security of the option (if applicable)
	Underlying string `json:"underlying,omitempty"`
	Strike float32 `json:"strike,omitempty"`
	OpenInterest float32 `json:"open_interest,omitempty"`
	ContractSize float32 `json:"contract_size,omitempty"`
	ExpirationDate string `json:"expiration_date,omitempty"`
	ExpirationType string `json:"expiration_type,omitempty"`
	OptionType string `json:"option_type,omitempty"`
}
