/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx4 struct for InlineResponse2Xx4
type InlineResponse2Xx4 struct {
	Stream InlineResponse2Xx4Stream `json:"stream,omitempty"`
}
