/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx1ExpirationsExpiration struct for InlineResponse2Xx1ExpirationsExpiration
type InlineResponse2Xx1ExpirationsExpiration struct {
	Date string `json:"date,omitempty"`
	Strikes InlineResponse2Xx1ExpirationsStrikes `json:"strikes,omitempty"`
}
