/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx3Symbols struct for InlineResponse2Xx3Symbols
type InlineResponse2Xx3Symbols struct {
	RootSymbol string `json:"rootSymbol,omitempty"`
	Options []string `json:"options,omitempty"`
}
