/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx1Expirations struct for InlineResponse2Xx1Expirations
type InlineResponse2Xx1Expirations struct {
	Date []string `json:"date,omitempty"`
	Expiration []InlineResponse2Xx1ExpirationsExpiration `json:"expiration,omitempty"`
}
