/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx5History struct for InlineResponse2Xx5History
type InlineResponse2Xx5History struct {
	Day []InlineResponse2Xx5HistoryDay `json:"day,omitempty"`
}
