/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// Quotes struct for Quotes
type Quotes struct {
	Quotes QuotesQuotes `json:"quotes,omitempty"`
}
