/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// ProfileProfile struct for ProfileProfile
type ProfileProfile struct {
	Account []ProfileProfileAccount `json:"account,omitempty"`
}
