/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx1 struct for InlineResponse2Xx1
type InlineResponse2Xx1 struct {
	Expirations InlineResponse2Xx1Expirations `json:"expirations"`
}
