/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2XxOptions struct for InlineResponse2XxOptions
type InlineResponse2XxOptions struct {
	Option []Option `json:"option,omitempty"`
}
