/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// InlineResponse2Xx5 struct for InlineResponse2Xx5
type InlineResponse2Xx5 struct {
	History InlineResponse2Xx5History `json:"history,omitempty"`
}
