/*
 * Tradier API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tradier
// QuotesQuotes struct for QuotesQuotes
type QuotesQuotes struct {
	Quote []Quote `json:"quote,omitempty"`
}
