# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tradier_urllib3.configuration import Configuration


class InlineResponse2XX3Symbols(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'root_symbol': 'str',
        'options': 'list[str]'
    }

    attribute_map = {
        'root_symbol': 'rootSymbol',
        'options': 'options'
    }

    def __init__(self, root_symbol=None, options=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse2XX3Symbols - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._root_symbol = None
        self._options = None
        self.discriminator = None

        if root_symbol is not None:
            self.root_symbol = root_symbol
        if options is not None:
            self.options = options

    @property
    def root_symbol(self):
        """Gets the root_symbol of this InlineResponse2XX3Symbols.  # noqa: E501


        :return: The root_symbol of this InlineResponse2XX3Symbols.  # noqa: E501
        :rtype: str
        """
        return self._root_symbol

    @root_symbol.setter
    def root_symbol(self, root_symbol):
        """Sets the root_symbol of this InlineResponse2XX3Symbols.


        :param root_symbol: The root_symbol of this InlineResponse2XX3Symbols.  # noqa: E501
        :type: str
        """

        self._root_symbol = root_symbol

    @property
    def options(self):
        """Gets the options of this InlineResponse2XX3Symbols.  # noqa: E501


        :return: The options of this InlineResponse2XX3Symbols.  # noqa: E501
        :rtype: list[str]
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this InlineResponse2XX3Symbols.


        :param options: The options of this InlineResponse2XX3Symbols.  # noqa: E501
        :type: list[str]
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2XX3Symbols):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2XX3Symbols):
            return True

        return self.to_dict() != other.to_dict()
