# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier_python
from tradier_python.models.inline_response2_xx4 import InlineResponse2XX4  # noqa: E501
from tradier_python.rest import ApiException

class TestInlineResponse2XX4(unittest.TestCase):
    """InlineResponse2XX4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2XX4
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier_python.models.inline_response2_xx4.InlineResponse2XX4()  # noqa: E501
        if include_optional :
            return InlineResponse2XX4(
                stream = tradier_python.models.inline_response_2_xx_4_stream.inline_response_2XX_4_stream(
                    url = '0', 
                    sessionid = '0', )
            )
        else :
            return InlineResponse2XX4(
        )

    def testInlineResponse2XX4(self):
        """Test InlineResponse2XX4"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
