# coding: utf-8

"""
    Tradier API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tradier_python
from tradier_python.models.inline_response2_xx2_strikes import InlineResponse2XX2Strikes  # noqa: E501
from tradier_python.rest import ApiException

class TestInlineResponse2XX2Strikes(unittest.TestCase):
    """InlineResponse2XX2Strikes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2XX2Strikes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tradier_python.models.inline_response2_xx2_strikes.InlineResponse2XX2Strikes()  # noqa: E501
        if include_optional :
            return InlineResponse2XX2Strikes(
                strike = [
                    1.337
                    ]
            )
        else :
            return InlineResponse2XX2Strikes(
        )

    def testInlineResponse2XX2Strikes(self):
        """Test InlineResponse2XX2Strikes"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
